apiVersion: v1
kind: Namespace
metadata:
  name:  uat
  labels:
    name: uat
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: res-quota
  namespace: uat
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "1Gi"
    limits.cpu: "2"
    limits.memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    # Anotacion para definir una causa de cambio en el deployment
    kubernetes.io/change-cause: Changes port to 120
  name: deployment-test
  namespace: uat
  labels:
    app: front
# Hasta aqui lo que es el deployment
# Desde aqui el replicaset
spec:
  # cuantos replicaSet queremos guardar en un futro
  #revisionHistoryLimit: 1
  replicas: 3
  selector:
    matchLabels:
      app: front
  # Desde aqui el pod que se creará
  template:
    metadata:
      labels:
        app: front
        namespace: uat
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          requests:
            memory: "500M"
            cpu: "500m"
          limits:
            memory: "500M"
            cpu: "500m"