apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: front
data:
  test: "hola"
  nginx:
    "server {
      listen 80;
      server_name  localhost;       
      location / {
      root   /usr/share/nginx/html;
      index  index.html index.htm;
    }
             
             error_page   500 502 503 504  /50x.html;
             location = /50x.html {
      root   /usr/share/nginx/html;
    }
    }"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
  labels:
    app: front
# Hasta aqui lo que es el deployment
# Desde aqui el replicaset
spec:
  # cuantos replicaSet queremos guardar en un futro
  #revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: front
  # Desde aqui el pod que se creará
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: test-container
          image: nginx:alpine
          volumeMounts:
            - name: nginx-volume
              mountPath: /etc/nginx/conf.d/
      volumes:
        - name: nginx-volume
          configMap:
            name: nginx-config