apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: 
    # Anotacion para definir una causa de cambio en el deployment
    kubernetes.io/change-cause: Changes port to 120
  name: frontend-k8s-hands-on
  labels:
    app: frontend
# Hasta aqui lo que es el deployment
# Desde aqui el replicaset
spec:
  # cuantos replicaSet queremos guardar en un futro
  #revisionHistoryLimit: 1
  replicas: 3
  selector:
    matchLabels:
      app: frontend
# Desde aqui el pod que se creará
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend-k8s-hands-on:v1
        # Para que mire si hay imagenes localmente
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-k8s-hands-on
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80